### ISSUE TITLE
Not able to config JDBC input

### ISSUE THREAD

**Issue by PavanRGowda** [logstash-plugins/logstash-input-jdbc#16]
Hello everyone, below is my configuration -

input {
    jdbc {
        jdbc_driver_class => "org.apache.derby.jdbc.EmbeddedDriver"	 
        jdbc_connection_string => "jdbc:derby://localhost:3306/test"
        jdbc_user => "root"
        jdbc_password => "password"
        statement => "select * from user"        		
     }
}

When I run the config file, I get the following error -

`The error reported is:` 
 ` org.apache.derby.jdbc.EmbeddedDriver not loaded`

Can anyone please help me resolve it? My current Java version is -

`java version "1.8.0_45"`
`Java(TM) SE Runtime Environment (build 1.8.0_45-b14)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)`

I'm also confused with the line ` jdbc_connection_string => "jdbc:derby:memory:testdb;create=true"`. I have database named `test`. How do I mention in the above connection_string?

**Comment by talevy** [comment]
No JDBC driver comes prepackaged within the plugin. To properly load a driver for use with the plugin, you must either add it to your java's classpath or supply the driver jar with the following parameter:

```
input {
  jdbc {
    jdbc_driver_library => "/path/to/derbyclient.jar"
    jdbc_driver_class => "org.apache.derby.jdbc.EmbeddedDriver"
    ...
  }
}
```

you can find the client library in the derby release downloads page here: http://db.apache.org/derby/releases/release-10.11.1.1.cgi.

let me know if that helps!

**Comment by PavanRGowda** [comment]
Thank you Talevy. It did solve my problem partially. I added the line  ` jdbc_driver_library => "/home/pavan/Downloads/db-derby-10.11.1.1-bin/lib/derby.jar" ` to my configuration file but I'm getting a new error now.
` The error reported is: `
 ` Sequel::DatabaseError: driver.new.connect returned nil: probably bad JDBC connection string`
`Java::JavaSql::SQLException: No suitable driver found for jdbc:derby://localhost:3306/memory:test;create=true`

I have a database by name `test` in phpmyAdmin and I want to pull data from it and index in elasticsearch. Can you please provide me the right connection string for it. Here's what I've tried ` jdbc_connection_string => "jdbc:derby://localhost:3306/memory:test;create=true" '

**Comment by talevy** [comment]
I am not familiar with phpmyAdmin. are you using a different database possibly, maybe MySQL?

**Comment by PavanRGowda** [comment]
I'm using MySQL but not able to overcome that error :(

**Comment by pafq** [comment]
@PavanRGowda 

First you need to download the correct JDBC driver. If you are using a MySQL Engine you the to use the MySQL JDBC Driver instead of Derby JDBC Driver. You can download the correct driver from here: https://dev.mysql.com/downloads/connector/j/5.1.html

After you get the driver you need to use the correct jdbc_connection_string. In you case it should be something like:

jdbc:mysql://localhost/test

With this Connection String you will connect to Database test on your localhost.
Also you need to use the correct driver_class, for MySQL it's: com.mysql.jdbc.Driver
If that don't work, try Java::com.mysql.jdbc.Driver

The driver name should be something like "mysql-connector-java-5.1.36-bin.jar"

**Comment by suyograo** [comment]
Hi, if you have more debugging questions, please move it to discuss. question/discuss here: https://discuss.elastic.co/c/logstash
