### ISSUE TITLE
sql_last_start Different Values

### ISSUE THREAD

**Issue by MichaelLiZhou** [logstash-plugins/logstash-input-jdbc#39]
Why is there 2 different values? This is very confusing now -- when I run in verbose mode for logstash test I see that 
sql_last_start=>2015-08-13 13:26:47 UTC

but I am also storing this in my .logtstash_since_lastrun which will be have a format of 
--- 2015-08-10 18:00:00.000000000 Z

which one is it?

**Comment by talevy** [comment]
@MichaelLiZhou 

That file is only updated when the pipeline shuts down. Not after every sql run. The value is updated in memory while the pipeline is running.

I have made an issue to update this so that this value is committed to the file after every statement execution.

https://github.com/logstash-plugins/logstash-input-jdbc/issues/41

does that answer your question?

**Comment by MichaelLiZhou** [comment]
Yeah that clears it up. Thank!
