### ISSUE TITLE
Make timeouts configurable

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-jdbc#62]
Currently, the timeouts (I think?) are hard-coded within Sequel to be 5 seconds. It could be useful to have this be configurable.

**Comment by ppf2** [comment]
Thanks for the quick turnaround on this @talevy !

**Comment by ppf2** [comment]
There is an issue in this PR which I can reproduce.  With the plugin updated (and even without specifying the new jdbc connection pool timeout property), it is failing at sequel/adapters/jdbc.rb:216:             

```
props.setProperty("password", opts[:password])
```

If I hardcode the password string instead of `opts[:password]` directly in the sequel code above, it works fine.  If opts[:password] is passed in, then it throws the exception:

```
The error reported is: 
  TypeError: cannot convert instance of class org.jruby.RubyObject to class java.lang.String
/Users/Pius/ELK/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/sequel-4.27.0/lib/sequel/adapters/jdbc.rb:216:in `connect'
```
